{"cdb":{"internalError":"Fehler beim Zugriff auf die Kundendatenbank","noCustomerFound":"Kunde nicht in der Datanbank gefunden.","idAlreadyExistsPleaseTryAgain":"Beim Anlegen des Kunden ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut."}}